name: Docker Image CI

on:
  push:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-world-web-app-test-ci:1.0
    - name: Docker Push
      run: docker push chayanbank/hello-world-web-app-test-ci:1.0
