name: ci
 
on:
 push:
   branches: [develop]
 
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        # https://github.com/docker/metadata-action
        uses: docker/metadata-action@v3
        with:
          images: ${{secrets.DOCKER_USER}}/hello-world-web-app-test-ci
          
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Push To quay.io
        uses: docker/build-push-action@v1
        with:
          image: ${{ secrets.QUAY_USER }}/test_devops
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          registry: quay.io/${{ secrets.QUAY_USER }}
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
