name: Merge branch with labeled
on:
  pull_request:
    types: [labeled]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Merge by labeled
        uses: devmasx/merge-branch@develop
        with:
          label_name: 'merged in main'
          target_branch: 'main'
          github_token: ${{ github.token }}
